### ISSUE TITLE
Big TO-DO list

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-application#84]
- [ ] #90
- [x] Get field hints working properly
    - [x] Identify which fields need hints, and come up with proper wording for each hint (@alexjlahr?)
- [x] Come up with image resize solution and implement so images are properly inserted into a Shopify product.
    - [ ] Review with Tom
- [x] Refactor pricing tier update so that existing pricing tiers are updated instead of replaced. 
- [x] Update "fractalize Image" form, so that if tiles are re-generated, old tiles are cleaned up from the database.
- [x] Add additional fields to "museum" collection, which will be needed in the email template (museum corporate name and tax ID)
- [x] For dimensions, use "inches" as the default
- [x] Instead of "Base Price", use "Pricing Tier 1"
- [x] #91
- [ ] #95
- [x] Allow for editing of art details (description, dimensions, note, year, etc.)
- [x] Once the art is live (perhaps as indicated by it being assigned to sales channels), hide the art edit form, and show a support request form to request changes.
- [x] Add drag-select functionality to DAB selector
    - [x] Refactor DAB selector so that "Maximum Update Depth Exceeded" error does not happen. 
- [ ] code review ComissionContext with Tom
- [x] Allow copy/paste into WYSIWYG editor
- [x] Build onOrderComplete hook. This should to the following
    - [x] Add the order number to the appropriate tile in the Database, Sync with product metafield "tiles"
    - [x] Generate the DAB image, save to database. Add path to DAB in the tile database
    - [x] #94
    - [x] Generate art image with crosshairs for social sharing (perhaps when certificate is created with puppeteer?)
    - [x] Mark order as "fulfilled"
- [x] #93
- [x] Add a "orders" page to museum app, showing table of latest orders (what to do with this info TBD)
    - Note: this is a rather code-intensive loop for filtering out non-museum orders. Review with Tom.
- [x] Add museum name as "Vendor"
- [ ] Make sure a proper message is displayed if the logged in use is not assigned to a museum.
    - note: I've implemented a redirect to a notification page if museum is not found, but this isn't the best solution. Probably something along the lines of "AuthGuard" that we can wrap every page in, right?
- [x] replace "loading products" text to spinner component.
- [x] Build API endpoint for retrieving order/dab data for the social share page. (Also todo, scaffold this out in the Hydrogen site.)
- [ ] #92
- [x] Add form validation throughout
- [x] Discuss reporting orders with Tom. This could turn out to be a challenge because orders are not easily filterable by what collection they are in (i.e. the museum)
- [x] Get Sentry and logging working properly. Closely look at all error catching throughout the museum application
