### ISSUE TITLE
To Do list for Paul

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-application#97]
**REQUIRED**
- [x] Add more meta fields to museum, add to museum edit page 
- [x] Design and implementation of the Social Share page
- [x] DAB Selector update so tooltip does not go off edge of screen
- [x] DAB Selector updates so that it works on mobile (remove zoom on mobile)
- [x] Implement custom order confirmation email 
- [x] Build an “onCheckout” hook that checks tile availability before checkout.   
- [x] Museum App - Apply copy changes throughout. 
- [x] Museum App: Apply designs provided by Jenny to museum App
- [x]  Museum App - Add “unavailable” field to DABS and randomly assign some tiles to it
- [x] Museum App - Send emails to comission admin for approval, and for request changes.
- [x] Museum App - Generation of PDF Certificate and crosshairs images using Puppeteer
- [x] Museum App Bug - Inventory updating when pricing tiers are set.
- [x] Museum App - Set unavailable tiles as non selectable for purchase (hydrogen dab selector)
- [x] Museum App - Add a way to remove initially unavailable tiles
- [x] Museum App - When a pricing tier is created, make sure it is set as "not a physical product"
- [x] Museum App - Big fix. base variant should be null instead of empty array
- [x] Can we make facebook share a popup?
- [x] Create new github branches for main, staging and development
- [x] Get error logging working properly in Sentry. 

**NOT REQUIRED**
- [ ] Set up the “invitation only” sign-up
- [ ] Manage permissions throughout. Access to firebase storage, Firestore, functions, etc.
- [ ] API Validation for Firestone functions (Shopify calls to API)
- [ ] Do we want any tests written? All existing tests are pretty much blown away since refactor.
- [ ] Update DAB selector so that zoom level changes depending on size of DABS, 
- [ ] Museum App - Order detail pages? Art specific order detail pages? 
- [x] Museum App - Refactor of pricing tier updates so that existing tiers are updated instead of deleted and re-created.
- [x] Museum App - Review DAB Selector so it isn’t so sluggish when there are many many dabs.

**MILESTONES**
- [x] All required tasks checked off
- [ ] Successfully complete manual QA
- [ ] Handoff

**FEATURE SUGGESTIONS**
For the process of adding new art, we could give the users the option to "add new artist". This would send information to a comission adminstrator, and the museum could continue creating the new art without being blocked.

**Comment by paulstroot** [comment]
Required items completed. Moving the rest to the discussions tab.
